export const projects = [
  {
    id: 1,
    title: "VOID HOUSE",
    location: "Kyoto, Japan",
    year: "2024",
    description: "A monolithic concrete residence designed to capture the emptiness of space. The structure features a central courtyard that acts as a light well, illuminating the raw concrete interiors with shifting shadows.",
    image: "https://images.unsplash.com/photo-1511818966892-d7d671e672a2?q=80&w=1200&auto=format&fit=crop",
  },
  {
    id: 2,
    title: "MONOLITH 09",
    location: "Berlin, Germany",
    year: "2023",
    description: "An experimental office complex in the heart of Berlin. The facade is composed of prefabricated ferro-concrete panels, creating a rhythmic pattern that repels the noise of the city.",
    image: "https://images.unsplash.com/photo-1486718448742-163732cd1544?q=80&w=1200&auto=format&fit=crop",
  },
  {
    id: 3,
    title: "OBSIDIAN TOWER",
    location: "New York, USA",
    year: "2025",
    description: "A super-tall residential skyscraper clad in black volcanic stone and dark glass. It stands as a silhouette against the skyline, absorbing light rather than reflecting it.",
    image: "https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?q=80&w=1200&auto=format&fit=crop",
  },
  {
    id: 4,
    title: "SILENT MUSEUM",
    location: "Oslo, Norway",
    year: "2024",
    description: "Designed for sound isolation, this museum houses acoustic art. The walls are 2-meter thick textured concrete, designed to dampen all external noise.",
    // Replaced broken URL with a reliable concrete interior
    image: "https://images.unsplash.com/photo-1518005052357-e9847508d4e4?q=80&w=1200&auto=format&fit=crop",
  },
  {
    id: 5,
    title: "CARBON VILLA",
    location: "Reykjavik, Iceland",
    year: "2023",
    description: "A net-zero energy home built into the volcanic landscape. The jagged roofline mimics the surrounding basalt columns, merging architecture with geology.",
    // Replaced broken URL with modern cabin
    image: "https://images.unsplash.com/photo-1449844908441-8829872d2607?q=80&w=1200&auto=format&fit=crop",
  },
  {
    id: 6,
    title: "AZURE DEPOT",
    location: "London, UK",
    year: "2025",
    description: "Adaptive reuse of a brutalist train depot into a tech campus. The project retains the massive structural beams while introducing suspended glass walkways.",
    image: "https://images.unsplash.com/photo-1565008576549-57569a49371d?q=80&w=1200&auto=format&fit=crop",
  },
  {
    id: 7,
    title: "ECHO CHAMBER",
    location: "Paris, France",
    year: "2024",
    description: "A performance hall designed entirely using algorithmic acoustics. The interior surfaces are computationally generated to reflect sound perfectly.",
    image: "https://images.unsplash.com/photo-1516550893923-42d28e5677af?q=80&w=1200&auto=format&fit=crop",
  },
  {
    id: 8,
    title: "NORDIC SPIRE",
    location: "Stockholm, Sweden",
    year: "2023",
    description: "A wooden skyscraper that pushes the boundaries of timber construction. It spirals upwards, maximizing daylight exposure for the apartments within.",
    image: "https://images.unsplash.com/photo-1487958449943-2429e8be8625?q=80&w=1200&auto=format&fit=crop",
  },
  {
    id: 9,
    title: "DUNE PAVILION",
    location: "Dubai, UAE",
    year: "2025",
    description: "A temporary structure for the Art Biennale, shaped like a sand dune frozen in time. Made from 3D printed sandstone.",
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=1200&auto=format&fit=crop",
  },
  {
    id: 10,
    title: "SOLAR FORGE",
    location: "Barcelona, Spain",
    year: "2024",
    description: "A research center for renewable energy. The entire roof acts as a solar concentrator, while the building form promotes natural ventilation.",
    // Replaced broken URL with abstract energy structure
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1200&auto=format&fit=crop",
  },
  {
    id: 11,
    title: "KINETIC LAB",
    location: "Seoul, South Korea",
    year: "2023",
    description: "A robotics laboratory with a facade that moves. Thousands of aluminum panels open and close based on sunlight intensity.",
    image: "https://images.unsplash.com/photo-1506158669146-619067262a00?q=80&w=1200&auto=format&fit=crop",
  },
  {
    id: 12,
    title: "ZERO POINT",
    location: "Tokyo, Japan",
    year: "2025",
    description: "A theoretical memorial space designed around a perfect circle of water. It represents the center of calm in the chaos of Tokyo.",
    image: "https://images.unsplash.com/photo-1510906594845-bc082582c8cc?q=80&w=1200&auto=format&fit=crop",
  },
];
